# Generated by Django 2.1.15 on 2022-02-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=255, unique=True)),
                ('content', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('water_mark', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
