version: "3"

services:
  watermark:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./watermark:/watermark
    command: >
     sh -c " python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=000011
      - SECRET_KEY=(8m(x+prok57353xgk3l+g16isv(f+yai#qg@t1b9oln8-m
    depends_on:
      - db


  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=000011
